apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app
spec:
  selector:
    matchLabels:
      app: cloud-gateway-app
  template:
    metadata:
      labels:
        app: cloud-gateway-app
    spec:
      initContainers:
      - name: wait-for-services
        image: busybox
        command:
          - 'sh'
          - '-c'
          - |
            until wget --spider $NOTIFICATION_MANAGEMENT_URL/actuator/info; do
              echo "waiting for task management"
              sleep 5
            done

            until wget --spider $TASK_SERVICE/health; do
              echo "waiting for task management"
              sleep 5
            done

            until wget --spider $USER_SERVICE/health; do
              echo "waiting for task management"
              sleep 5
            done
        env:
          - name: NOTIFICATION_MANAGEMENT_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: notification_management_url  
          - name: TASK_SERVICE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: task_management_url  
          - name: USER_SERVICE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: user_management_url  

      containers:
      - name: cloud-gateway-app
        image: "ECR_REGISTRY/api-gateway:IMAGE_TAG" 
        imagePullPolicy: Always
        ports:
        - containerPort: 8060
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: config_server_url
        - name: ZIPKIN_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: zipkin_url  
        - name: TASK_SERVICE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: task_management_url  
        - name: USER_SERVICE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: user_management_url                
---

apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: cloud-gateway-app
  ports:
  - port: 80
    targetPort: 8060

