
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: mysql_root_password
        volumeMounts:
        - name: mysql-init-db
          mountPath: /docker-entrypoint-initdb.d
        - name: ebs-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: ebs-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2


---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - port: 3306

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-db
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS myapp_db;
