apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-management-app
spec:
  selector:
    matchLabels:
      app: notification-management-app
  template:
    metadata:
      labels:
        app: notification-management-app
    spec:
      initContainers:
      - name: wait-for-services
        image: busybox
        command:
          - 'sh'
          - '-c'
          - |

            echo "Waiting for RabbitMQ..."
            until nc -z $RABBITMQ_HOST 5672; do echo "waiting for RabbitMQ"; sleep 5; done;
            echo "RabbitMQ is ready."

            echo "Waiting for Zipkin..."
            until wget --spider $ZIPKIN_URL/zipkin/; do
              echo "waiting for Zipkin"
              sleep 5
            done
            echo "Zipkin is ready."

            echo "Waiting for Config Server..."
            until wget --spider $CONFIG_SERVER_URL/notificationmanagement/default; do
              echo "waiting for Config Server"
              sleep 5
            done
            echo "Config Server is ready."
        env:
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: rabbitmq_host  
          - name: ZIPKIN_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: zipkin_url
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: config_server_url

      containers:
      - name: notification-management-app
        image: "ECR_REGISTRY/notification-management:IMAGE_TAG" 
        imagePullPolicy: Always

        ports:
        - containerPort: 8020
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: config_server_url
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: rabbitmq_host  
        - name: GMAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: gmail_username       
        - name: GMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: gmail_password    
        - name: ZIPKIN_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: zipkin_url 

---

apiVersion: v1
kind: Service
metadata:
  name: notification-management-svc
spec:
  selector:
    app: notification-management-app
  ports:
  - port: 80
    targetPort: 8020

