apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: task-management-app
  template:
    metadata:
      labels:
        app: task-management-app
    spec:
      imagePullSecrets:
      - name: my-ecr-secret
      initContainers:
      - name: wait-for-services
        image: busybox
        command:
          - 'sh'
          - '-c'
          - |
            echo "Waiting for MongoDB..."
            until nc -z $MONGODB_HOST 27017; do echo "waiting for MongoDB"; sleep 5; done;
            echo "MongoDB is ready."

            echo "Waiting for Zipkin..."
            until wget --spider $ZIPKIN_URL/zipkin/; do
              echo "waiting for Zipkin"
              sleep 5
            done
            echo "Zipkin is ready."

            echo "Waiting for Config Server..."
            until wget --spider $CONFIG_SERVER_URL/taskmanagement/default; do
              echo "waiting for Config Server"
              sleep 5
            done
            echo "Config Server is ready."


            echo "Waiting for RabbitMQ..."
            until nc -z $RABBITMQ_HOST 5672; do echo "waiting for RabbitMQ"; sleep 5; done;
            echo "RabbitMQ is ready."
        env:
          - name: MONGODB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: mongodb_host
          - name: ZIPKIN_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: zipkin_url
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: config_server_url
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: rabbitmq_host
      containers:
      - name: task-management-app
        image: ECR_REGISTRY/task-management:IMAGE_TAG

        imagePullPolicy: Always

        ports:
        - containerPort: 8000
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: config_server_url
        - name: SERVICE_NAME
          value: "taskmanagement"     
        - name: ZIPKIN_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: zipkin_url 
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: mongo_root_username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: mongo_root_password
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mongodb_host  
        - name: RABBITMQ_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: rabbitmq_uri  
                                             
---

apiVersion: v1
kind: Service
metadata:
  name: task-management-svc
spec:
  selector:
    app: task-management-app
  ports:
  - port: 80
    targetPort: 8000
