spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      allow-override: true
      override-none: true
      server:
        enabled: true
        native:
          search-locations: classpath:/config/

server:
  port: 8088

  instance:
    appname: config-server
    instance-id: config-server
    preferIpAddress: true

logging:
  level:
    org:
      springframework:
        core:
          env: DEBUG

