server:
  port: 8060

spring:
  cloud:
    gateway:
      routes:
        # Route for authentication paths without JWT filter
        - id: auth-service
          uri: lb://usermanagement
          predicates:
            - Path=/auth/**

        # Route for paths that require authentication
        - id: user-management
          uri: lb://usermanagement
          predicates:
            - Path=/api/users/**
          filters:
            - JWTAuthorizationFilter

          # Route for paths that require authentication
        - id: task-management
          uri: lb://taskmanagement
          predicates:
            - Path=/api/tasks/**
          filters:
            - JWTAuthorizationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761//eureka/
  instance:
    appname: api-gateway
    instance-id: api-gateway
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: info,health
  health:
    show-details: always
