server:
  port: 8060

spring:
  cloud:
    gateway:
      routes:
        # Route for authentication paths without JWT filter
        - id: auth-service
          uri: ${USER_SERVICE}
          predicates:
            - Path=/auth/**

        # Route for paths that require authentication
        - id: user-management
          uri: ${USER_SERVICE}
          predicates:
            - Path=/api/users/**
          filters:
            - JWTAuthorizationFilter

          # Route for paths that require authentication
        - id: task-management
          uri: ${TASK_SERVICE}
          predicates:
            - Path=/api/tasks/**
          filters:
            - JWTAuthorizationFilter

    
management:
  zipkin:
    tracing:  
      endpoint: ${ZIPKIN_BASE_URL}
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: info,health
  health:
    show-details: always
