server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  instance:
    appname: notification-management
    instance-id: notification-management
    preferIpAddress: true

management:
  zipkin:
    tracing:  
      endpoint: ${ZIPKIN_BASE_URL}
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    rabbit:
      enabled: true

spring:
  rabbitmq:
    host: ${RABBITMQ_URL:localhost}
    username: guest
    password: guest
    exchange: task_exchange
    queue: task_queue
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  zipkin:
    enabled: true
    baseUrl: ${ZIPKIN_BASE_URL}