server:
  port: 8000

mongodb:
  username: ${MONGODB_USERNAME}
  password: ${MONGODB_PASSWORD}
  host: ${MONGODB_HOST}
  
rabbitmq:
  host: ${RABBITMQ_URI}


# Zipkin configuration
zipkin:
  baseUrl: ${ZIPKIN_BASE_URL}

