server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761//eureka/
    healthcheck:
      enabled: true
      url: http://localhost:8080/health

  instance:
    hostname: localhost
    appname: user-management
    instance-id: user-management

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myapp_db
    username: root
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update  

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: info,health
  health:
    show-details: always
    db:
      enabled: true

