server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
      url: http://${USER_MANAGEMENT:localhost}:8080/health
  instance:
    appname: user-management
    instance-id: user-management
    preferIpAddress: true

spring:
  datasource:
    url: jdbc:mysql://${SQL_HOST:localhost}:3306/myapp_db
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update  


management:
  zipkin:
    tracing:  
      endpoint: ${ZIPKIN_BASE_URL}
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: info,health
  health:
    show-details: always
    db:
      enabled: true

